### PR TITLE
fix(examples): fix form-field-custom-control

### LINKED ISSUE #14810: Creating a custom form field control documentation example not working
#### What is the expected behavior?
The component described on
https://material.angular.io/guide/creating-a-custom-form-field-control
is not working inside a formGroup

#### What is the current behavior?
When you type a telephone number the formGroup isn't updating with the typed data.

#### What are the steps to reproduce?
Open
https://stackblitz.com/edit/angular-splcaa-ue6ba4?file=app%2Fform-field-custom-control-example.html

When typing a telephone number you see the form data not being updated

### PR DESCRIPTION
**Pull request by swseverance**
* Update `MyTelInput` to implement `ControlValueAccessor` interface
* Resolves #14810

### CODE REVIEW

**Comment by swseverance** [comment]
@crisbeto would you mind taking a look? Thank you

File: src/material-examples/form-field-custom-control/form-field-custom-control-example.ts [hunk 1]
```diff
@@ -116,4 +126,32 @@ export class MyTelInput implements MatFormFieldControl<MyTel>, OnDestroy {
...
+  }
+
+  _handleInput(): void {
+    this.onChange(this.parts.value);
+  }
+
+  _handleBlur(event: FocusEvent): void {
+    const inputs = Array.from(this.elRef.nativeElement.querySelectorAll('input'));
+
+    if (!inputs.some(input => event.relatedTarget === input)) {
```
Comment (crisbeto) [inline src/material-examples/form-field-custom-control/form-field-custom-control-example.ts]: Isn't this guaranteed to always be `true`? The only inputs that have the listener are the ones inside the `elRef` from what I can tell.

Comment (swseverance) [reply src/material-examples/form-field-custom-control/form-field-custom-control-example.ts]: @crisbeto there are scenarios in which this evaluates to `false`. For example, if the user clicks an entirely different form control (which receives focus) then the blur event's `relatedTarget` will not be equal to one of the three `input` elements defined in `MyTelInput`'s template.

My rationale is that if the user is changing focus between the three input elements there's no need to mark the form control as `touched`. However, if they focus on any element other than one of the three inputs it is appropriate to mark the form control as `touched`.

Comment (crisbeto) [reply src/material-examples/form-field-custom-control/form-field-custom-control-example.ts]: That makes sense, although I remember `relatedTarget` being flaky on some browsers. This would be a bit cleaner if you used the CDK focus monitor with subtree monitoring.

Comment (swseverance) [reply src/material-examples/form-field-custom-control/form-field-custom-control-example.ts]: @crisbeto thanks. The code is cleaner when relying on the CDK focus monitor.

**Comment by Alex-Samari** [comment]
I tried adding validators.required to the 'parts' form group and while it works for the form control, the form component that is using this form control won't recognize the validation. Can someone implement the validation please?

**Comment by swseverance** [comment]
@Alex-Samari did you happen to try this by modifying the StackBlitz on https://material.angular.io/guide/creating-a-custom-form-field-control? It appears that the changes I made are not yet deployed to StackBlitz.

**Comment by Alex-Samari** [comment]
@swseverance No, I'm working on my own project and followed the changes you made in the gitHub repo. The value accessor works and I'm able to change the value of the custom form control but when I add validators to the form group, I can't access those validators in the parent component that is using the custom form control

**Comment by swseverance** [comment]
@Alex-Samari Is there a branch I can look at? You can just email me directly if you'd like. My email is on my profile.

**Comment by Alex-Samari** [comment]
@swseverance I couldn't find your email but here's a repository I made of what I have:
https://github.com/Alex-Samari/Angular-custom-form-field

I'm using the custom-tel-control inside my form component

**Comment by swseverance** [comment]
@Alex-Samari I didn't implement validation as part of `MyTelInput` because it seemed like it was beyond the scope of what the tutorial was intended to cover. However, I created a stack blitz with a custom validator that hopefully achieves what you're looking for.

https://stackblitz.com/edit/angular-byencm?file=app%2Fform-field-custom-control-example.ts

my email is swseverance@gmail.com

**Comment by Alex-Samari** [comment]
@swseverance Thank you! Validation is working perfectly fine now 👍
