### PR TITLE
fix(input): do not focus input element twice

### LINKED ISSUE #12849: Input time can't click at minutes to edit in Firefox
#### Bug:
I think its a low bug but the behavior is diffrent as expceted.
The behavior of the input control type time is diffrent inside the mat-form-field.
Currently in Firefox you can't start edit the minutes with mouse.

#### What is the expected behavior?
Click at the minutes to edit them, the cursor should be set by the minutes.

#### What is the current behavior?
Click at the minutes to edit them, the cursor starts by the hours.

#### What are the steps to reproduce?
use FireFox and an input inside a mat-form-field

`<mat-form-field>
    <input matInput placeholder="Time" type="time">
  </mat-form-field>`

#### What is the use-case or motivation for changing an existing behavior?
Usability

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 6.4.6
FireFox 61.0.2 (64-Bit)

#### Is there anything else we should know?
With the arrow keys you can navigate to the minutes and edit them

### PR DESCRIPTION
**Pull request by DevVersion**
* Currently if a user clicks on a input, the element receives focus and the `click` event bubbles up. Once it reaches the `<mat-form-field>`, the click event will cause the `onContainerClick` method to be invoked. This method then manually focused the input element (again). Resulting in unexpected behavior for time inputs in Firefox.

**Note**: There is no good way to test this behavior because we cannot dispatch a click event that sets `focus` and also explicitly selects the `minute` field of a time input. E2E tests don't work either because we run against Chrome headless and not Firefox.

Fixes #12849

### CODE REVIEW

File: src/lib/input/input.ts [hunk 1]
```diff
@@ -368,5 +368,12 @@ export class MatInput extends _MatInputMixinBase implements MatFormFieldControl<
    * Implemented as part of MatFormFieldControl.
    * @docs-private
    */
-  onContainerClick() { this.focus(); }
+  onContainerClick() {
+    // Do not re-focus the input element if the element is already focused. Otherwise it can happen
+    // that someone clicks on a time input and the cursor resets to the "hours" field while the
+    // "minutes" field was actually clicked. See: https://github.com/angular/material2/issues/12849
+    if (!this.focused) {
```
Comment (mmalerba) [inline src/lib/input/input.ts]: Do we need similar logic for other `MatFormFieldControl` components (e.g. select, chips)

Comment (DevVersion) [reply src/lib/input/input.ts]: It guess it wouldn't hurt. There might be also people that use chips with a time input.

I can update it tomorrow (or have a follow-up PR)

Comment (DevVersion) [reply src/lib/input/input.ts]: Just checked. The chip list already has a proper check for that. Please have another look.
