### PR TITLE
fix(menu): menu content data being cleared when lazy-loaded content is reused between nested triggers

### LINKED ISSUE #12467: matMenuTriggerData not working with nested menu
#### Bug
Switching between submenus doesn't pass the [matMenuTriggerData] properly.
It passes only to the first selected submenu, but the data is empty when selecting other submenus after the first.
nestedmenu

#### What are the steps to reproduce?

Sample code: https://stackblitz.com/edit/angular-nevxe3?file=app%2Fnested-menu-example.html
```html
<button mat-button [matMenuTriggerFor]="animals">Animal index</button>

<mat-menu #animals="matMenu">
  <button mat-menu-item [matMenuTriggerFor]="submenu" [matMenuTriggerData]="{category: 'vertebrates'}">Vertebrates</button>
  <button mat-menu-item [matMenuTriggerFor]="submenu" [matMenuTriggerData]="{category: 'invertebrates'}">Invertebrates</button>
</mat-menu>

<mat-menu #submenu="matMenu">
  <ng-template matMenuContent let-category="category">
    <button mat-menu-item>You selected: {{category}}</button>
  </ng-template>
</mat-menu>
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0
Material 6.4.2

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes an issue where a nested menu with lazy-loaded that is reused between multiple triggers will clear its content once an alternate trigger is hovered. The issue comes from the fact that we wait for the exit animation to finish before we detach the content, which ends up detaching the content of the new trigger as well.

**Note:** I spent some time on trying to get a proper test that covers this issue, but I wasn't able to get something that fails when we expect it to. The issue is very closely tied to the animations module and the async animations which are being flushed synchronously in tests.

Fixes #12467.

### CODE REVIEW

File: src/lib/menu/menu-trigger.ts [hunk 1]
```diff
@@ -243,11 +243,18 @@ export class MatMenuTrigger implements AfterContentInit, OnDestroy {
       menu._resetAnimation();
 
       if (menu.lazyContent) {
+        menu.lazyContent._attached.pipe(take(1)).subscribe(() => console.log('re-attached'));
```
Comment (jelbourn) [inline src/lib/menu/menu-trigger.ts]: Debugging statement?

Comment (crisbeto) [reply src/lib/menu/menu-trigger.ts]: ops, I forgot about that one. It's removed.
