### PR TITLE
fix(progress-spinner): Rename ProgressCircle to ProgressSpinner

### LINKED ISSUE #1495: Rename `md-progress-circle` to `md-progress-spinner`
`md-spinner` stays the same.

### PR DESCRIPTION
**Pull request by tinayuangao**
Closes #1495 

R: @jelbourn

### CODE REVIEW

File: src/lib/progress-spinner/progress-spinner.ts [hunk 1]
```diff
@@ -28,28 +28,28 @@ const endIndeterminate = 80;
...
 
 
 /**
- * <md-progress-circle> component.
+ * <md-progress-spinner> component.
  */
 @Component({
   moduleId: module.id,
-  selector: 'md-progress-circle, mat-progress-circle',
+  selector: 'md-progress-spinner, mat-progress-spinner',
```
Comment (jelbourn) [inline src/lib/progress-spinner/progress-spinner.ts]: We need to leave the old selectors as well so we can more easily migrate existing google projects

File: src/lib/progress-spinner/progress-spinner.ts [hunk 2]
```diff
@@ -28,28 +28,28 @@ const endIndeterminate = 80;
...
     '[attr.aria-valuemax]': '_ariaValueMax',
   },
-  templateUrl: 'progress-circle.html',
-  styleUrls: ['progress-circle.css'],
+  templateUrl: 'progress-spinner.html',
+  styleUrls: ['progress-spinner.css'],
   changeDetection: ChangeDetectionStrategy.OnPush,
 })
-export class MdProgressCircle implements OnDestroy {
+export class MdProgressSpinner implements OnDestroy {
```
Comment (jelbourn) [inline src/lib/progress-spinner/progress-spinner.ts]: You can add at the bottom of this file
```ts
/** @deprecated */
export {MdProgressSpinner as MdProgressCircle};
/** @deprecated */
export {MdProgressSpinnerModule as MdProgressCircleModule};
// same for other symbols
```

this will let people continue using the old symbols and let us migrate them incrementally.

**Comment by tinayuangao** [comment]
Make selectors `md-progress-circle` and `mat-progress-circle` work. Thanks for review! Please take another look.

**Comment by tinayuangao** [comment]
Added  progress-circle.ts. PTAL. Thanks!

**Comment by jelbourn** [comment]
LGTM
