### PR TITLE
fix(ng-add): install added packages

### LINKED ISSUE #11159: `ng add @angular/material`
Moved from https://github.com/angular/angular-cli/issues/10627

---

### Versions
```
Angular CLI: 6.0.0
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router
```

### Repro steps

* Step 1: `ng add @angular/material`
* Step 2 It will update multiple files and add `@angular/material` and `@angular/cdk` to `package.json`

### Observed behavior
```
It will install @angular/material but won't install @angular/cdk
```

### Desired behavior
```
It should either install both or none.
```

### PR DESCRIPTION
**Pull request by clydin**
Fixes #11159

### CODE REVIEW

File: src/lib/schematics/shell/index.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
-import {chain, noop, Rule, Tree} from '@angular-devkit/schematics';
+import {chain, noop, Rule, Tree, SchematicContext} from '@angular-devkit/schematics';
+import { NodePackageInstallTask } from '@angular-devkit/schematics/tasks';
```
Comment (amcdnl) [inline src/lib/schematics/shell/index.ts]: nit: Remove spaces around import

Comment (clydin) [reply src/lib/schematics/shell/index.ts]: Done.
