### PR TITLE
fix(dialog): don't assign aria-label to close button if button has text

### LINKED ISSUE #11084: MatDialogClose shouldn't set aria-label if it has text
In cases where a button has both text and a `mat-dialog-close`, the aria-label should not be set because it trumps the text. We should only set the label if either: the text is empty, or, the only text is within a `mat-icon`.

It _would_ make sense to add something like `Closes the dialog` with `aria-describedby` (via `AriaDescriber`) if we add an API to customize the message for i18n.

### PR DESCRIPTION
**Pull request by crisbeto**
No longer adds the `aria-label` to the `mat-dialog-close` directive, if the element that it's being applied to has text. This prevents the label from being read instead of the button text.

Fixes #11084.

### CODE REVIEW

File: src/lib/dialog/dialog-content-directives.ts [hunk 1]
```diff
@@ -56,6 +62,9 @@ export class MatDialogClose implements OnInit, OnChanges {
       // be resolved at constructor time.
       this.dialogRef = getClosestDialog(this._elementRef, this._dialog.openDialogs)!;
     }
+
+    const buttonText = this._elementRef.nativeElement.innerText;
+    this._hasText = !!buttonText && buttonText.trim().length > 0;
```
Comment (crisbeto) [inline src/lib/dialog/dialog-content-directives.ts]: A note on this: this could technically become inaccurate if the button has a data binding that starts off with a value, but then gets cleared. I decided not to handle that case, because of the potential performance implications.

File: src/lib/dialog/dialog-content-directives.ts [hunk 2]
```diff
@@ -56,6 +62,9 @@ export class MatDialogClose implements OnInit, OnChanges {
       // be resolved at constructor time.
       this.dialogRef = getClosestDialog(this._elementRef, this._dialog.openDialogs)!;
     }
+
+    const buttonText = this._elementRef.nativeElement.innerText;
```
Comment (jelbourn) [inline src/lib/dialog/dialog-content-directives.ts]: I had been thinking we could special-case `mat-icon` and ignore its text if it's present, but I realized we can actually just ignore the text if it's a `mat-icon-button`.

Comment (crisbeto) [reply src/lib/dialog/dialog-content-directives.ts]: Done. I also reworded it a bit so it's more clear about what it does.

File: src/lib/dialog/dialog-content-directives.ts [hunk 3]
```diff
@@ -56,6 +62,11 @@ export class MatDialogClose implements OnInit, OnChanges {
       // be resolved at constructor time.
       this.dialogRef = getClosestDialog(this._elementRef, this._dialog.openDialogs)!;
     }
+
+    const element = this._elementRef.nativeElement;
+
+    this._hasAriaLabel = element.hasAttribute('mat-icon-button') ||
+                         element.innerText.trim().length === 0;
```
Comment (jelbourn) [inline src/lib/dialog/dialog-content-directives.ts]: Use `textContent` since it doesn't require a style calculation?

**Comment by josephperrott** [comment]
@crisbeto In the check to determine if an `aria-label` should be applied during `ngOnInit`, on line 72 we should also check to confirm that the aria-label has not changed.

Even if there is text content inside of the button, the user should be able to have screen readers read their own aria-label rather than button content.

Something like this should work:
```js
this._hasAriaLabel = (
    !buttonTextContent || 
    buttonTextContent.trim().length === 0 || 
    this.ariaLabel !== 'Close dialog');
```

**Comment by crisbeto** [comment]
@josephperrott [that's what this line does](https://github.com/angular/material2/pull/11093/files#diff-f0f896040c69a7d463a7a689f135d825R32). If the consumer specified an `aria-label`, we won't override anything.

**Comment by josephperrott** [comment]
Correct, however I think currently the only paths to `_hasAriaLabel` being `true` is if the element is a `MatIconButton` or if there is no text content, or the text content is empty once trimmed.

We need to cover the case where an `aria-label` is provided by the user **and** the button has text content.

**Comment by crisbeto** [comment]
Ah I see. I've changed it to use the `ngOnChanges` instead.

**Comment by crisbeto** [comment]
@josephperrott can you take another look at this one?

**Comment by andrewseguin** [comment]
Hey @crisbeto - looks like we've got a small problem on this PR. If the button has an aria-label, it is getting removed when there is button text.

The flow is that `ngOnChanges` is called and sets `_hasAriaLabel` to true because the input is true. But then `ngOnInit` runs and sets it back to false since there is button text.

**Comment by crisbeto** [comment]
Updated to avoid having the `_hasAriaLabel` be reset by `ngOnInit`.

File: src/lib/dialog/dialog.spec.ts [hunk 4]
```diff
@@ -1466,11 +1483,13 @@ class ContentElementDialog {}
       <mat-dialog-content>Lorem ipsum dolor sit amet.</mat-dialog-content>
       <mat-dialog-actions>
         <button mat-dialog-close>Close</button>
+        <button class="close-without-text" mat-dialog-close></button>
+        <button class="close-icon-button" mat-icon-button mat-dialog-close>exit</button>
         <button class="close-with-true" [mat-dialog-close]="true">Close and return true</button>
         <button
```
Comment (stevenyxu) [inline src/lib/dialog/dialog.spec.ts]: How do you think `<button mat-dialog-close aria-label="foo">bar</button>` should behave? It would be great to call this out. Is it possible the current implementation wipes out the aria-label? I'd propose that this is surprising.
