### PR TITLE
fix(overlay): better handling of server-side rendering

### LINKED ISSUE #8412: Get document is undefined with SSR in MatSnackBar
When trying to use MatSnackBar with SSR getting 'document is undefined` error when prerendering pages.
Angular 5 and @angular/material": "2.0.0-beta.12

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes multiple server-side rendering issues in the overlay that were causing errors when an overlay is opened in Universal.

Fixes #8412.

### CODE REVIEW

File: src/cdk/a11y/live-announcer.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import {
   SkipSelf,
   OnDestroy,
 } from '@angular/core';
-import {Platform} from '@angular/cdk/platform';
+import {DOCUMENT} from '@angular/platform-browser';
```
Comment (jelbourn) [inline src/cdk/a11y/live-announcer.ts]: The `DOCUMENT` from platform-browser is deprecated; should use the one from `@angular/common` instead

File: src/cdk/a11y/live-announcer.ts [hunk 2]
```diff
@@ -28,14 +28,12 @@ export class LiveAnnouncer implements OnDestroy {
...
       @Optional() @Inject(LIVE_ANNOUNCER_ELEMENT_TOKEN) elementToken: any,
-      platform: Platform) {
-    // Only do anything if we're on the browser platform.
-    if (platform.isBrowser) {
-      // We inject the live element as `any` because the constructor signature cannot reference
-      // browser globals (HTMLElement) on non-browser environments, since having a class decorator
-      // causes TypeScript to preserve the constructor signature types.
-      this._liveElement = elementToken || this._createLiveElement();
-    }
+      @Inject(DOCUMENT) private _document: any) {
```
Comment (jelbourn) [inline src/cdk/a11y/live-announcer.ts]: I think you can do:
```ts
@Inject(DOCUMENT) private _document: Document|Document
```
It shouldn't preserve the type info for "computed" types; I think this will trick it will still giving type safety

File: src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts [hunk 3]
```diff
@@ -81,15 +84,18 @@ export class OverlayKeyboardDispatcher implements OnDestroy {
...
 
 /** @docs-private */
 export const OVERLAY_KEYBOARD_DISPATCHER_PROVIDER = {
   // If there is already an OverlayKeyboardDispatcher available, use that.
   // Otherwise, provide a new one.
   provide: OverlayKeyboardDispatcher,
-  deps: [[new Optional(), new SkipSelf(), OverlayKeyboardDispatcher]],
+  deps: [
+    [new Optional(), new SkipSelf(), OverlayKeyboardDispatcher],
+    DOCUMENT as InjectionToken<any> // We need to use the InjectionToken somewhere to keep TS happy
```
Comment (jelbourn) [inline src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts]:
```ts
// Coerce to `InjectionToken` so that the `deps` match the "shape"
// of the type expected by Angular
```

File: src/cdk/overlay/position/global-position-strategy.ts [hunk 4]
```diff
@@ -147,10 +149,10 @@ export class GlobalPositionStrategy implements PositionStrategy {
     const element = this._overlayRef.overlayElement;
 
     if (!this._wrapper && element.parentNode) {
-      this._wrapper = document.createElement('div');
-      this._wrapper.classList.add('cdk-global-overlay-wrapper');
-      element.parentNode.insertBefore(this._wrapper, element);
-      this._wrapper.appendChild(element);
+      this._wrapper = this._document.createElement('div');
+      this._wrapper!.classList.add('cdk-global-overlay-wrapper');
```
Comment (jelbourn) [inline src/cdk/overlay/position/global-position-strategy.ts]: Put the `!` on the assignment for `_wrapper`?
```ts
this._wrapper = this._document.createElement('div')!;
```

Comment (crisbeto) [reply src/cdk/overlay/position/global-position-strategy.ts]: TS can't figure it out when assigning to a property.

File: src/cdk/a11y/live-announcer.ts (hunk 2 above)
Comment (crisbeto) [reply src/cdk/a11y/live-announcer.ts]: That doesn't seem to work in AoT.

**Comment by crisbeto** [comment]
Addressed the feedback @jelbourn.
