### PR TITLE
fix(bottom-sheet): allow disableClose to be updated after opened

### LINKED ISSUE #14708: Add the availability to disable the close of a bottomSheet programatically once is opened.
Add the availability to disable the close of a bottomSheet programatically once is opened (like in dialogs).

### PR DESCRIPTION
**Pull request by crisbeto**
Allows for the `disableClose` value of a bottom sheet to be updated after it has been opened, similarly to `MatDialog`.

Fixes #14708.

### CODE REVIEW

File: src/lib/bottom-sheet/bottom-sheet-ref.ts [hunk 1]
```diff
@@ -42,6 +45,7 @@ export class MatBottomSheetRef<T = any, R = any> {
     // @breaking-change 8.0.0 `_location` parameter to be removed.
     _location?: Location) {
     this.containerInstance = containerInstance;
+    this.disableClose = containerInstance.bottomSheetConfig.disableClose;
```
Comment (josephperrott) [inline src/lib/bottom-sheet/bottom-sheet-ref.ts]: Will this potentially change the behavior since you are setting the value in the class instead of reading it from the object at the time of the check?

Comment (crisbeto) [reply src/lib/bottom-sheet/bottom-sheet-ref.ts]: It won't change the behavior, because the old approach only read it once on init.

Comment (josephperrott) [reply src/lib/bottom-sheet/bottom-sheet-ref.ts]: Ahh, yes because it set up the subscription based on that. Makes sense.
