### PR TITLE
fix(form-field): make outline appearance work in situations where the…

### LINKED ISSUE #10498: form-field: outline gap calculated incorrectly with setTimeout
Repro courtesy of @fxck: https://stackblitz.com/edit/material2-textarea-outline-problem-in-dialog?file=app%2Fdialog.ts

Workaround is to call `updateOutlineGap` on the form field with the incorrect gap size. But ideally we could make it so the user doesn't have to do this

### PR DESCRIPTION
**Pull request by mmalerba**
… form field is not initially in the DOM.

fixes #10498

### CODE REVIEW

File: src/lib/form-field/form-field.ts [hunk 1]
```diff
@@ -419,6 +419,9 @@ export class MatFormField extends _MatFormFieldMixinBase
         // getBoundingClientRect isn't available on the server.
         return;
       }
+      if (!document.contains(this._elementRef.nativeElement)) {
```
Comment (crisbeto) [inline src/lib/form-field/form-field.ts]: This one'll probably throw in Universal.

File: src/lib/form-field/form-field.ts [hunk 2]
```diff
@@ -195,6 +195,8 @@ export class MatFormField extends _MatFormFieldMixinBase
 
   _outlineGapStart = 0;
 
+  _initialGapCalculated = false;
```
Comment (crisbeto) [inline src/lib/form-field/form-field.ts]: Rather than adding another property, couldn't we get away with checking that the gap is greater than 0?

File: src/lib/form-field/form-field.ts (hunk 1 above)
Comment (mmalerba) [reply src/lib/form-field/form-field.ts]: The line above is returning if we're not in the browser

File: src/lib/form-field/form-field.ts (hunk 2 above)
Comment (mmalerba) [reply src/lib/form-field/form-field.ts]: Currently that would cause a check loop for other types of form-field, since they set the gap to `0`. I could set it to `1` or some other number in that case since its not really used, but this just seemed clearer
