### PR TITLE
fix(select): don't restore focus unless an option was selected

### LINKED ISSUE #8915: multiple select problem
Hi,

with multiple select i had some problem with positioning of the "overlay" (the select panel with options) on a scrolling page (forgive my english, i know, i am not good at all on it)

https://stackblitz.com/edit/angular-material2-issue-fyg1vr

this is what i got

1) scroll down
2) click on a select, leave it open
3) scroll some more, click on another select, i get teleported back to the previous position
but hte selec panel disappear

antoher things

1) randomly scroll
2) click -> select multiple times
3) scroll to bottom, open a new select, the scroll go crazy and the overlay of the select get positioned randomly on top position

on mobile chrome it's evern worst.

test was with chrome, latest version, osx. angular 5, material.io 5

### PR DESCRIPTION
**Pull request by crisbeto**
Currently `mat-select` always restores focus to its trigger whenever the panel is closed. This can be problematic, because the user might've scrolled away and restoring focus would scroll the page back up. These changes switch to only restoring focus if the user made a selection.

Fixes #8915.

### CODE REVIEW

**Comment by andrewseguin** [comment]
Needs rebase

File: src/lib/select/select.ts [hunk 1]
```diff
@@ -297,8 +297,12 @@ export class MatSelect extends _MatSelectMixinBase implements AfterContentInit,
     },
   ];
 
+  private _hasFocus = false;
+
   /** Whether the select is focused. */
-  focused = false;
+  get focused() {
```
Comment (jelbourn) [inline src/lib/select/select.ts]: Uncovered during presubmit: this makes `focused` readonly, which is a breaking change
(apparently some apps set it manually for some reason)

**Comment by crisbeto** [comment]
Reverted the breaking change @jelbourn.
