### PR TITLE
fix(progress-circle): remove references to window

### LINKED ISSUE #837: ReferenceError: window is not defined at now in progress-circle.js
#### What is the expected behavior?
md-spinner should render on server side when *shellRender is used.

#### What is the current behavior?
```ReferenceError: window is not defined
    at now (/home/developer/hybris-store-angular2/node_modules/@angular2-material/progress-circle/progress-circle.js:255:9)
    at MdSpinner.MdProgressCircle._animateCircle (/home/developer/hybris-store-angular2/node_modules/@angular2-material/progress-circle/progress-circle.js:141:25)
    at animate (/home/developer/hybris-store-angular2/node_modules/@angular2-material/progress-circle/progress-circle.js:170:19)
    at MdSpinner.MdProgressCircle._startIndeterminateAnimation (/home/developer/hybris-store-angular2/node_modules/@angular2-material/progress-circle/progress-circle.js:179:13)
    at MdSpinner.Object.defineProperty.set [as mode] (/home/developer/hybris-store-angular2/node_modules/@angular2-material/progress-circle/progress-circle.js:118:22)
    at new MdSpinner (/home/developer/hybris-store-angular2/node_modules/@angular2-material/progress-circle/progress-circle.js:226:19)
    at DebugAppView._View_AppComponent3.createInternal (AppComponent.template.js:237:25)
    at DebugAppView.AppView.create (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/view.js:87:21)
    at DebugAppView.create (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/view.js:299:44)
    at TemplateRef_.createEmbeddedView (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/template_ref.js:57:14)
    at ViewContainerRef_.createEmbeddedView (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/view_container_ref.js:99:35)
    at ShellRender.ngOnInit (/home/developer/hybris-store-angular2/node_modules/@angular/app-shell/shell-render.directive.js:24:33)
    at DebugAppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:78:110)
    at DebugAppView.AppView.detectChanges (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/view.js:234:14)
    at DebugAppView.detectChanges (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/view.js:339:44)
    at DebugAppView.AppView.detectViewChildrenChanges (/home/developer/hybris-store-angular2/node_modules/@angular/core/src/linker/view.js:260:19)
ERROR CONTEXT:
[object Object]```

#### Which versions of Angular, Material, OS, browsers are affected?
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/forms": "0.1.1",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "@angular2-material/core": "^2.0.0-alpha.6",
    "@angular2-material/progress-circle": "^2.0.0-alpha.6",
    "@angular2-material/toolbar": "^2.0.0-alpha.6",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },

#### Is there anything else we should know?
While using angular-cli with --mobile

### PR DESCRIPTION
**Pull request by crisbeto**
* Removes the references to `window` in the progressCircle component.
* A couple of minor coding style tweaks.

Fixes #837.

### CODE REVIEW

File: src/components/progress-circle/progress-circle.ts [hunk 1]
```diff
@@ -124,13 +124,13 @@ export class MdProgressCircle implements OnDestroy {
   get mode() {
     return this._mode;
   }
-  set mode(m: ProgressCircleMode) {
-    if (m == 'indeterminate') {
+  set mode(_mode: ProgressCircleMode) {
```
Comment (jelbourn) [inline src/components/progress-circle/progress-circle.ts]: The underscore is used for private/internal class members. Function arguments should not use it.

File: src/components/progress-circle/progress-circle.ts [hunk 2]
```diff
@@ -250,8 +250,8 @@ function clamp(v: number) {
  * Returns the current timestamp either based on the performance global or a date object.
  */
 function now() {
-  if (window.performance && window.performance.now) {
-    return window.performance.now();
+  if (typeof performance !== 'undefined' && performance.now) {
```
Comment (jelbourn) [inline src/components/progress-circle/progress-circle.ts]: Is there a reason to change this? It seems like change for the sake of change.

File: src/components/progress-circle/progress-circle.ts (hunk 1 above)
Comment (crisbeto) [inline src/components/progress-circle/progress-circle.ts]: Got it, will revert.

File: src/components/progress-circle/progress-circle.ts (hunk 2 above)
Comment (crisbeto) [inline src/components/progress-circle/progress-circle.ts]: The point of the PR was to remove the references to `window`. Just doing `if (performance && performance.now)` would throw an exception if the client doesn't have the `performance` object.

Comment (jelbourn) [inline src/components/progress-circle/progress-circle.ts]: I mean what is the purpose of removing the reference to `window`?

Comment (crisbeto) [inline src/components/progress-circle/progress-circle.ts]: Ah, in #837 the user mentioned that there's a runtime exception when rendering server-side, because of the references to `window`.

Comment (jelbourn) [inline src/components/progress-circle/progress-circle.ts]: Oh, I missed the linked issue. Thanks.

**Comment by jelbourn** [comment]
LGTM

**Comment by crisbeto** [comment]
The CI seems to be failing because of some unrelated Node error.
