### PR TITLE
fix(button-toggle): fix button toggle with 0 value not checked

### LINKED ISSUE #11279: [Button Toggle] Initial value of [0] does not work when values are indicies
https://stackblitz.com/edit/angular-ulbznt?file=app/button-toggle-exclusive-example.html

In the example, the first option should be selected.

### PR DESCRIPTION
**Pull request by tinayuangao**
Fixes #11279

### CODE REVIEW

File: src/lib/button-toggle/button-toggle.ts [hunk 1]
```diff
@@ -264,7 +264,8 @@ export class MatButtonToggleGroup extends _MatButtonToggleGroupMixinBase impleme
     }
 
     if (this.multiple && Array.isArray(this._rawValue)) {
-      return !!this._rawValue.find(value => toggle.value != null && value === toggle.value);
+      const match = this._rawValue.find(value => toggle.value != null && value === toggle.value);
+      return typeof match !== 'undefined';
```
Comment (jelbourn) [inline src/lib/button-toggle/button-toggle.ts]: You should be able to do `return match != null`, which will capture `null` and `undefined` without any of the other falsy values

File: src/lib/button-toggle/button-toggle.ts [hunk 2]
```diff
@@ -264,7 +264,8 @@ export class MatButtonToggleGroup extends _MatButtonToggleGroupMixinBase impleme
     }
 
     if (this.multiple && Array.isArray(this._rawValue)) {
-      return !!this._rawValue.find(value => toggle.value != null && value === toggle.value);
+      const match = this._rawValue.find(value => toggle.value != null && value === toggle.value);
+      return match != null;
```
Comment (crisbeto) [inline src/lib/button-toggle/button-toggle.ts]: You can just return here: `return !!this._rawValue.find(...)`.

File: src/lib/button-toggle/button-toggle.ts [hunk 3]
```diff
@@ -264,7 +264,7 @@ export class MatButtonToggleGroup extends _MatButtonToggleGroupMixinBase impleme
     }
 
     if (this.multiple && Array.isArray(this._rawValue)) {
-      return !!this._rawValue.find(value => toggle.value != null && value === toggle.value);
+      return null != this._rawValue.find(value => toggle.value != null && value === toggle.value);
```
Comment (jelbourn) [inline src/lib/button-toggle/button-toggle.ts]: If you only care about the *presence* of the value, you can use `some` instead of `find`:
```ts
return this._rawValue.some(v => toggle.value != null && v === toggle.value);
```

Comment (tinayuangao) [reply src/lib/button-toggle/button-toggle.ts]: Thanks. Updated.
