### PR TITLE
fix(slide-toggle): remove view encapsulation

### LINKED ISSUE #1343: md-slide-toggle cannot be styled from outside due to encapsulation
#### Bug:
md-slide-toggle has no `encapsulation: ViewEncapsulation.None` set so it cannot be easily styled from the outside.

#### What is the expected behavior?
`encapsulation: ViewEncapsulation.None` should be turn on.
It should be easy to override the component styles

#### What is the current behavior?
Cannot easily override component style

#### Which versions of Angular, Material, OS, browsers are affected?
Alpha.9

### PR DESCRIPTION
**Pull request by DevVersion**
* Removes the ViewEncapsulation from the slide-toggle component to allow developer overwriting the styles easly.

Fixes #1343.

### CODE REVIEW

**Comment by jelbourn** [comment]
LGTM

File: src/lib/slide-toggle/slide-toggle.ts [hunk 1]
```diff
@@ -61,7 +63,7 @@ export class MdSlideToggle implements AfterContentInit, ControlValueAccessor {
   private _uniqueId = `md-slide-toggle-${++nextId}`;
   private _checked: boolean = false;
   private _color: string;
-  _hasFocus: boolean = false;
+  private _hasFocus: boolean = false;
```
Comment (jelbourn) [inline src/lib/slide-toggle/slide-toggle.ts]: This is used in a host binding, so making it private will break AoT

Comment (DevVersion) [inline src/lib/slide-toggle/slide-toggle.ts]: Didn't know about that. Thanks - I reverted it and also added a comment for it.

**Comment by jelbourn** [comment]
LGTM
