### PR TITLE
fix(tooltip): wrong position when using OnPush change detection

### LINKED ISSUE #3497: mdTooltip wrong position when used inside a component with OnPush
https://gist.run/?id=2df959fa72c4d9839dd4e621d73a0f73

image

my guess is that it tries to calculate the position before the content is set (you can actually see it flicker as an empty tooltip for a few milliseconds)

cc @andrewseguin

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the tooltip having a wrong position if it is inside a component with `OnPush` change detection. The issue was due to the fact that when `OnPush` is used, the tooltip text isn't rendered at the moment when the element is positioned.

Fixes #3497.

### CODE REVIEW

File: src/lib/tooltip/tooltip.ts [hunk 1]
```diff
@@ -461,4 +463,13 @@ export class TooltipComponent {
...
     }
   }
+
+  /**
+   * Ensures that the tooltip text has rendered. Mainly used for rendering the initial text
+   * before positioning a tooltip, which can be problematic in components with OnPush change
+   * detection.
+   */
+  _updateView(): void {
+    this._changeDetectorRef.detectChanges();
```
Comment (DevVersion) [inline src/lib/tooltip/tooltip.ts]: Is there any reason why you use `detectChanges` instead of `markForCheck`?

Comment (crisbeto) [inline src/lib/tooltip/tooltip.ts]: Hmm, I thought I tried it and it wasn't working. Looking at it again, it seems like it's the same. I'll change it.

File: src/lib/tooltip/tooltip.spec.ts [hunk 2]
```diff
@@ -432,6 +432,15 @@ describe('MdTooltip', () => {
...
     }));
+
+    it('should have rendered the tooltip text on init', fakeAsync(() => {
+      dispatchFakeEvent(buttonElement, 'mouseenter');
+      fixture.detectChanges();
+      tick(0);
+
+      const tooltipElement = overlayContainerElement.querySelector('.mat-tooltip') as HTMLElement;
+      expect(tooltipElement.textContent).toContain('initial tooltip message');
+    }));
```
Comment (jelbourn) [inline src/lib/tooltip/tooltip.spec.ts]: Does there need to be a test component w/ `OnPush` that would have exhibited the original behavior?

Comment (crisbeto) [inline src/lib/tooltip/tooltip.spec.ts]: It already is using the one that we use for testing `OnPush`: https://github.com/angular/material2/pull/3671/files#diff-90d01e051e22bab8526ca923091f589fR391
