### PR TITLE
fix(tooltip): ensure tooltip stays within viewport

### LINKED ISSUE #5428: Bug: Tooltip truncated in the left if the host element is near the left of the screen
#### Bug:

Tooltip displayed at the bottom truncated in the left if the host element is near the left of the screen

#### What is the expected behavior?

The left margin of the tooptip should be zero or slightly above zero, rather than currently negative.

#### What is the current behavior?

Characters in the left get truncated.

#### What are the steps to reproduce?

In https://material.angular.io/components/tooltip/examples with Plunker, make the selection the host get closer to the left through remove the left margin in the css, and the tooltip position set to the bottom, and also make the content of the tooltip slightly longer.

#### What is the use-case or motivation for changing an existing behavior?

There are some elements on the left need tooltip to be displayed at the bottom of the element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Material2 Beta 7. All browsers are affected.

### PR DESCRIPTION
**Pull request by crisbeto**
* Adds a fallback position to ensure that tooltips can't go outside the viewport.
* Refactors the `transform-origin` logic to depend on the overlay position, instead of the tooltip position.

Fixes #5428.

### CODE REVIEW

File: src/lib/tooltip/tooltip.ts [hunk 1]
```diff
@@ -316,52 +327,60 @@ export class MdTooltip implements OnDestroy {
     this._tooltipInstance = null;
   }
 
-  /** Returns the origin position based on the user's position preference */
-  _getOrigin(): OriginConnectionPosition {
-    if (this.position == 'above' || this.position == 'below') {
-      return {originX: 'center', originY: this.position == 'above' ? 'top' : 'bottom'};
-    }
-
+  /** Returns the origin position and a fallback position based on the user's position preference */
```
Comment (andrewseguin) [inline src/lib/tooltip/tooltip.ts]: Can you describe that the fallback is the inverted position of the origin?

**Comment by crisbeto** [comment]
Addressed the feedback.

**Comment by mmalerba** [comment]
please rebase

**Comment by mmalerba** [comment]
sorry, needs rebase again
