### PR TITLE
fix(menu): unable to bind to xPosition and yPosition

### LINKED ISSUE #4169: Can't bind to 'xPosition' since it isn't a known property of 'md-menu'.
Is there any reason [these](https://github.com/angular/material2/blob/master/src/lib/menu/menu-directive.ts#L57
) are `@Attribute`s instead of `@Input`s?

I'm trying to pass down the position from a parent component.

@kara @jelbourn

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes not being able to use data bindings on the `xPosition` and `yPosition` properties.

**Note:** These changes could be considered breaking, if somebody was implementing the `MdMenuPanel` interface.

Fixes #4169.

### CODE REVIEW

**Comment by willshowell** [comment]
Fixes #4169

File: src/lib/menu/menu-directive.ts [hunk 1]
```diff
@@ -45,27 +49,42 @@ export class MdMenu implements AfterContentInit, MdMenuPanel, OnDestroy {
...
+  /** List of the items inside of a menu. */
   @ContentChildren(MdMenuItem) items: QueryList<MdMenuItem>;
+
+  /** Whether the menu should overlap its trigger. */
   @Input() overlapTrigger = true;
 
-  constructor(@Attribute('xPosition') posX: MenuPositionX,
-              @Attribute('yPosition') posY: MenuPositionY,
-              @Attribute('x-position') deprecatedPosX: MenuPositionX,
+  constructor(@Attribute('x-position') deprecatedPosX: MenuPositionX,
```
Comment (kara) [inline src/lib/menu/menu-directive.ts]: While we're in here, let's remove the deprecated positions?

File: src/lib/menu/menu-directive.ts [hunk 2]
```diff
@@ -81,6 +100,12 @@ export class MdMenu implements AfterContentInit, MdMenuPanel, OnDestroy {
     }
   }
 
+  ngOnChanges(changes: SimpleChanges) {
+    if (changes['xPosition'] || changes['yPosition']) {
+      this.setPositionClasses();
```
Comment (kara) [inline src/lib/menu/menu-directive.ts]: Curious why we are adding a hook to call `setPositionClasses` when we already have the setters above. I think it might be cleaner not to break up the logic.

Comment (crisbeto) [inline src/lib/menu/menu-directive.ts]: Not sure I understood the question. The setters aren't dealing with the classes at all.

Comment (kara) [inline src/lib/menu/menu-directive.ts]: The classes need to be updated whenever the xPosition or the yPosition changes.  For that reason, it makes more sense to me to call this method in the xPosition and yPosition setters rather than creating a hook just to listen for changes on those properties.

**Comment by crisbeto** [comment]
Addressed the feedback @kara.

**Comment by willshowell** [comment]
Also fixes #1329

**Comment by mmalerba** [comment]
There are some teams in google that extend MdMenuPanel, we will need to update them before merging
