### PR TITLE
fix(autocomplete): remove old classes when classlist has changed

### LINKED ISSUE #15179: Autocomplete - Allow updating the panel class dynamically
#### Please describe the feature you would like to request.
The class input on the autocomplete control allows for setting classes on the autocomplete panel, but the setter does not allow dynamic removal of any classes that are previously set. 

https://github.com/angular/material2/blob/master/src/lib/autocomplete/autocomplete.ts#L153

The setter should parse the string input and remove keys from the _classList object that are no longer in the value

#### What is the use-case or motivation for this proposal?
A class needs to be set on the autocomplete panel depending on if the input has a value or not so that we can show a help card

### PR DESCRIPTION
**Pull request by crisbeto**
Currently we have some logic that syncs the classes between the autocomplete host element and the panel, however this logic doesn't account for classes being removed.

Fixes #15179.

### CODE REVIEW

File: src/lib/autocomplete/autocomplete.ts [hunk 1]
```diff
@@ -153,9 +153,16 @@ export class MatAutocomplete extends _MatAutocompleteMixinBase implements AfterC
...
+      this._classList = value.split(' ').reduce((classList, className) => {
+        classList[className.trim()] = true;
+        return classList;
+      }, {} as {[key: string]: boolean});
+    } else {
+      this._classList = {};
     }
+
+    this._setVisibilityClasses(this._classList);
+    this._elementRef.nativeElement.className = '';
```
Comment (jelbourn) [inline src/lib/autocomplete/autocomplete.ts]: I see it was like this before, but doesn't this wipe out `.mat-autocomplete`?

Comment (crisbeto) [reply src/lib/autocomplete/autocomplete.ts]: It does, but that's the point. This is the element that is left behind in the view after it provides the `ng-template` for the overlay panel.
