### PR TITLE
fix(input): input not focused on click in IE if clicked outside of the native input element

### LINKED ISSUE #15093: Input looks ready for input but does not have curosr
#### What is the expected behavior?
Cursor is in the input and its focused

#### What is the current behavior?
element is not accepting input
image

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/animations": "^7.2.3",
    "@angular/cdk": "^7.3.0",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.3",
    "@angular/material": "^7.3.0",
    "typescript": "3.1.6"

    IE 11.2724

### PR DESCRIPTION
**Pull request by macjohnny**
fixes #15093

### CODE REVIEW

File: src/lib/input/input.ts [hunk 1]
```diff
@@ -311,7 +311,14 @@ export class MatInput extends _MatInputMixinBase implements MatFormFieldControl<
...
   /** Focuses the input. */
   focus(): void {
+    // fix IE11 not able to focus programmatically with css style -ms-user-select: none
+    // see https://github.com/angular/material2/issues/15093
+    this._elementRef.nativeElement.style[<any>'-ms-user-select'] = 'auto';
+
     this._elementRef.nativeElement.focus();
+
+    // reset IE11 fix css style
+    this._elementRef.nativeElement.style[<any>'-ms-user-select'] = '';
```
Comment (crisbeto) [inline src/lib/input/input.ts]: Rather than doing this in JS, it might be better if we either reset the `-ms-user-select` in CSS or we never emitted it to begin with. This styling is there as a nice-to-have anyway.

Comment (mmalerba) [reply src/lib/input/input.ts]: Yeah I think we should just remove the problematic style. Doing this will allow people to focus it by calling `.focus()` on the component, but it could still prevent focus in other situations

Comment (macjohnny) [reply src/lib/input/input.ts]: @crisbeto @mmalerba thanks for the review. I updated the PR according to your suggestions to override the problematic styling in CSS for IE only. Could you please have another look at this PR?

**Comment by macjohnny** [comment]
in the dev-app, this can be tested with the "Only placeholder" input in the "Floating labels" section

File: src/lib/form-field/form-field-input.scss [hunk 2]
```diff
@@ -89,6 +89,12 @@
     // happen, however it's possible to do it when clicking on a disabled input (see #13479).
     @include user-select(none);
 
+    &:-ms-input-placeholder {
+      // fix IE11 not able to focus programmatically with css style -ms-user-select: none
+      // see https://github.com/angular/material2/issues/15093
+      -ms-user-select: text;
```
Comment (crisbeto) [inline src/lib/form-field/form-field-input.scss]: Actually on a second though, maybe we should set it to `auto`? That's the default value from the browser.

Comment (macjohnny) [reply src/lib/form-field/form-field-input.scss]: @crisbeto I initially thought so, too, but [MSDN](https://msdn.microsoft.com/en-us/library/hh781492(v=vs.85).aspx) states that the initial value of `-ms-user-select` is `text` and `auto` is not an allowed property.

Comment (crisbeto) [reply src/lib/form-field/form-field-input.scss]: Interesting. I guess that's why it has a vendor prefix.

Comment (macjohnny) [reply src/lib/form-field/form-field-input.scss]: @crisbeto by the way, is there any chance to have a quick chat with you about your PR that adds a header to mat select? Please ping me on gitter.im. We have built a component that adds a search input field for mat select (see https://github.com/bithost-gmbh/ngx-mat-select-search), which has >10k downloads per month, and I would like to talk about integrating / building this feature in material itself.

Comment (crisbeto) [reply src/lib/form-field/form-field-input.scss]: The reason my PR hasn't moved much in a long time is that we wanted to get the accessibility story for `mat-select` right before doing it, because we might've had to make some API changes. We should be able to get back to it once #14430 goes through.

Comment (macjohnny) [reply src/lib/form-field/form-field-input.scss]: Thanks for the response. Is there any chance I could contribute a native material implementation of https://github.com/bithost-gmbh/ngx-mat-select-search?
