### PR TITLE
fix(ngc): _onDragStart/End are called with one param

### LINKED ISSUE #1112: Some components don't build with ngc
one example:
```
third_party/javascript/angular2_material/src/lib/slide-toggle/slide-toggle.ngfactory.ts:300:29: Supplied parameters do not match any signature of call target.
third_party/javascript/angular2_material/src/lib/slide-toggle/slide-toggle.ngfactory.ts:310:29: Supplied parameters do not match any signature of call target.
```

because `_onDragStart` does not accept parameters:
https://github.com/angular/material2/blob/d6f3e7773c0fcea008e48807617fa0e39263049e/src/lib/slide-toggle/slide-toggle.ts#L216
but is called with one parameter:
https://github.com/angular/material2/blob/d6f3e7773c0fcea008e48807617fa0e39263049e/src/lib/slide-toggle/slide-toggle.html#L7

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #1112

### CODE REVIEW

File: src/lib/slide-toggle/slide-toggle.ts [hunk 1]
```diff
@@ -213,7 +213,7 @@ export class MdSlideToggle implements AfterContentInit, ControlValueAccessor {
 
 
   /** TODO: internal */
-  _onDragStart() {
+  _onDragStart(event: Event) {
```
Comment (DevVersion) [inline src/lib/slide-toggle/slide-toggle.ts]: - Why don't we remove the parameters from the HTML instead (This does not show any linter warnings / infos etc.)
- Or make it consistent with the `onDrag` function, by using `HammerInput` instead? (to get proper autocompletion)

Comment (alexeagle) [inline src/lib/slide-toggle/slide-toggle.ts]: good idea, removed the parameter at the callsite instead.

Comment (DevVersion) [inline src/lib/slide-toggle/slide-toggle.ts]: Thank you :)

**Comment by jelbourn** [comment]
LGTM
