### PR TITLE
fix(select): panel in multiple mode not overlapping trigger

### LINKED ISSUE #4943: Select overlay in multiple mode needs to extend further
This is based on the discussion from https://github.com/angular/material2/issues/4171: because the left offset of a select in multiple mode is larger, we need to increase the overlay width to allow it to overlap the entire trigger.

### PR DESCRIPTION
**Pull request by crisbeto**
* Fixes the select panel in multiple mode not overlapping the trigger completely.
* Reformats the select.html to make it a little more manageable.

Fixes #4943.

### CODE REVIEW

File: src/lib/select/select.ts [hunk 1]
```diff
@@ -838,16 +838,18 @@ export class MdSelect implements AfterContentInit, OnDestroy, OnInit, ControlVal
     const overlayRect = this.overlayDir.overlayRef.overlayElement.getBoundingClientRect();
     const viewportRect = this._viewportRuler.getViewportRect();
     const isRtl = this._isRtl();
+    const extraWidth = this.multiple ? SELECT_MULTIPLE_PANEL_PADDING_X + SELECT_PANEL_PADDING_X :
```
Comment (kara) [inline src/lib/select/select.ts]: Nit: `extraWidth` is a bit vague. How about `paddingWidth` ?
