### PR TITLE
fix(radio): forward focus to native input

### LINKED ISSUE #6029: Focus-trap start marker doesn't work when focus is redirected to an internal element
If `cdk-focus-start` / `-end` is applied to, e.g., `<md-radio-button>`, the focus trap will try to focus the actual `md-radio-button` element. This is problematic because the radio button actually defers focus/keyboard interaction to an internal `<input type="radio">` element.

### PR DESCRIPTION
**Pull request by mmalerba**
fixes #6029

### CODE REVIEW

File: src/lib/radio/radio.ts [hunk 1]
```diff
@@ -332,6 +332,7 @@ export const _MdRadioButtonMixinBase = mixinColor(mixinDisableRipple(MdRadioButt
     '[class.mat-radio-checked]': 'checked',
     '[class.mat-radio-disabled]': 'disabled',
     '[attr.id]': 'id',
+    '(focus)': '_inputElement.nativeElement.focus()',
```
Comment (DevVersion) [inline src/lib/radio/radio.ts]: I think it would be really beneficial to have a comment for this. What do you think?

A comment that explains that normally the native element should be focused; But for the focus-trap there is an exception

**Comment by jelbourn** [comment]
@tinayuangao @DevVersion any idea what's up w/ the screenshots?
