### PR TITLE
fix(a11y): add all providers to forRoot

### LINKED ISSUE #2189: A11yModule.forRoot() does not include providers from MdPlatformModule
Each module's `forRoot` should include *all* of the providers in its dependency chain.

### PR DESCRIPTION
**Pull request by crisbeto**
Adds all of the necessary providers to the `A11yModule`.

Fixes #2189.

### CODE REVIEW

File: src/lib/core/a11y/index.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export class A11yModule {
   static forRoot(): ModuleWithProviders {
     return {
       ngModule: A11yModule,
-      providers: A11Y_PROVIDERS,
+      providers: PlatformModule.forRoot().providers.concat(A11Y_PROVIDERS),
```
Comment (crisbeto) [inline src/lib/core/a11y/index.ts]: Ah nice, TIL. It's changed.

**Comment by jelbourn** [comment]
LGTM
