### PR TITLE
fix(sort): remove arrow when sort header is disabled

### LINKED ISSUE #14986: Disabled mat-sort-header still takes space (prevents centering)
#### What is the expected behavior?
The sort-headers should be outright removed from the DOM, or given "display: none"

#### What is the current behavior?
The sort arrows are still there, with `opacity: 0` what happens is that they are not wired to appear or be clickable when hovered.
However, when the `mat-header-cell` is given center or right alignment, it gets a bit offset, as the arrow’s size is also taken into account.

#### What are the steps to reproduce?
Create a material table with `mat-sort-header` and `disabled`
https://stackblitz.com/angular/byxxpgxkqkl (forked from documentation)

In this example, all 3 Name, W(eight) and S(symbol) columns are centered.
Name is a normal column, and renders just well.
W is mat-sort-header and disabled, and clearly offset from the contents of the column.
S has a .css workaround to fix it, outright hiding the arrows.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Current, as of this writing

#### Is there anything else we should know?
- When using disabled, all the mat-sort stuff is still in the DOM. This makes it harder to style, especially if the table has mixed sortabled/non-sortable header.
- This also happens using the "component" approach of creating a table (using <mat-table>)
- This css only code also fixes the issue (both <table> and <mat-table>):
```css
.mat-sort-header-button[disabled] ~ .mat-sort-header-arrow {
  display: none
}
```
If the fix is complicated, applying at least this by default in MatTable’s style would be nice.

### PR DESCRIPTION
**Pull request by crisbeto**
Doesn't render the arrow for a disabled header, unless it is the active one. This prevents it from taking up space when it won't be used.

Fixes #14986.

### CODE REVIEW

File: src/lib/sort/sort-header.ts [hunk 1]
```diff
@@ -289,4 +289,9 @@ export class MatSortHeader extends _MatSortHeaderMixinBase
 
     return this._sort.direction == 'asc' ? 'ascending' : 'descending';
   }
+
+  /** Gets whether the arrow inside the sort header should be rendered. */
```
Comment (andrewseguin) [inline src/lib/sort/sort-header.ts]: Minor nit: Remove the "Gets" and just have `"Whether the arrow..."`
