### PR TITLE
fix(overlay): unable to use overlay provider during app initialization

### LINKED ISSUE #10967: MatSnackbar causes provider to  throw cyclic dependency error
While defining a service provider in module with

```
providers: [
    GlobalErrorHandlerService,
    {
      provide: ErrorHandler,
      useExisting: GlobalErrorHandlerService
    }
  ]
```

where 'GlobalErrorHandlerService' requires 'MatSnackbar' causes the compiler to throw a cyclic dependency error

```
Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
Evaluating main.ts
Booting application
```

Steps to reproduce:
StackBlitz: https://stackblitz.com/edit/matsnackbar-error

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a cyclic dependency error that is being thrown when the `Overlay` is injected during app initialization.

Fixes #10967.

### CODE REVIEW

File: src/cdk/overlay/overlay.ts [hunk 1]
```diff
@@ -111,7 +112,12 @@ export class Overlay {
    * @returns A portal outlet for the given DOM element.
    */
   private _createPortalOutlet(pane: HTMLElement): DomPortalOutlet {
+    // We have to resolve the ApplicationRef later in order to allow people
+    // to use overlay-based providers during app initialization.
+    if (!this._appRef) {
```
Comment (jelbourn) [inline src/cdk/overlay/overlay.ts]: This has been like this for a long time- did something change in Angular 6.0?

Comment (crisbeto) [reply src/cdk/overlay/overlay.ts]: I don't think anything has changed, but it's just not that common of a use case. FWIW, we had something similar for dialog, but I had a hard time reproducing it in the demo app so I never got around to fixing it https://github.com/angular/material2/issues/10304.
