### PR TITLE
fix(schematics): do not generate invalid stylesheet files

### LINKED ISSUE #15164: Material schematics should generate .css files for some settings
If the user's project is configured to use `.sass` (not `.scss`) or Stylus, we should emit plan CSS files since our generated source is not valid in those syntaxes. Both `.scss` and `.less` are supersets of CSS, so those are fine.

### PR DESCRIPTION
**Pull request by devversion**
Currently whenever someone specified Stylus or Sass as the
default style extension for their Angular CLI project, the CDK/
Material schematics incorrectly generate files with that given
extension. This is problematic because the schematic style
templates are written in CSS and therefore are not compatible
with Stylus or Sass (which are not supersets of CSS unlike less, scss)

Fixes #15164

### CODE REVIEW

File: src/cdk/schematics/utils/build-component.ts [hunk 1]
```diff
@@ -40,6 +40,12 @@ import {getProjectFromWorkspace} from './get-project';
 import {getDefaultComponentOptions} from './schematic-options';
 import {ts} from './version-agnostic-typescript';
 
+/**
+ * List of supported styles which are CSS supersets. All supported CLI style extensions can be
+ * found here: angular/angular-cli/master/packages/schematics/angular/ng-new/schema.json#L118-L122
+ */
+const supportedCssSupersets = ['scss', 'less'];
```
Comment (devversion) [inline src/cdk/schematics/utils/build-component.ts]: @jelbourn I decided to do in a safelist-fashion as "technically" the CLI could add new unsupported style extensions which will then break. This way we guarantee that we _never_ generate invalid stylesheets.

Comment (jelbourn) [reply src/cdk/schematics/utils/build-component.ts]: That's the right call :+1:

File: src/cdk/schematics/utils/build-component.ts [hunk 2]
```diff
@@ -195,6 +201,14 @@ export function buildComponent(options: ComponentOptions,
     validateName(options.name);
     validateHtmlSelector(options.selector!);
 
+    // In case the specified style extension is not part of the supported CSS supersets,
+    // we generate the stylesheets with the "css" extension. This ensures that we don't
+    // accidentally generate invalid stylesheets (e.g. drag-drop-comp.styl) which will
+    // break the Angular CLI project. See: https://github.com/angular/material2/issues/15164
+    if (options.styleext !== 'css' && !supportedCssSupersets.includes(options.styleext!)) {
```
Comment (jelbourn) [inline src/cdk/schematics/utils/build-component.ts]: Could you just add `css` to the allowed list to simplify this check?

Comment (devversion) [reply src/cdk/schematics/utils/build-component.ts]: Done. I also changed the variable name since `css` being a superset of `css` sounds weird 👍
