### PR TITLE
fix(datepicker): toggle should inherit color from mat-form-field through mat-datepicker

### LINKED ISSUE #10221: datepicker: document new features for 6.0.0
- [x] New color option #9407
- [x] New `@Output`s #9678
- [x] Icon customization #9487
- [x] Year selection mode #8565

### PR DESCRIPTION
**Pull request by mmalerba**
Also adds docs for color feature.

Fixes #10221

### CODE REVIEW

File: src/lib/datepicker/datepicker.ts [hunk 1]
```diff
@@ -153,7 +153,15 @@ export class MatDatepicker<D> implements OnDestroy, CanColor {
   @Input() startView: 'month' | 'year' = 'month';
 
   /** Color palette to use on the datepicker's calendar. */
-  @Input() color: ThemePalette;
+  @Input()
+  get color(): ThemePalette {
+    return this._color ||
+        (this._datepickerInput  ? this._datepickerInput ._getThemePalette() : undefined);
```
Comment (crisbeto) [inline src/lib/datepicker/datepicker.ts]: There's an extra space before the question mark and the `._getThemePalette`.
