### PR TITLE
fix(list): adds focus state for nav-list items

### LINKED ISSUE #323: Add focus styling for anchors in md-nav-list

### PR DESCRIPTION
**Pull request by robertmesserle**
closes #323

Note: More discussion needed on list items with multiple actions.

R: @jelbourn @kara

### CODE REVIEW

File: src/components/list/list.ts [hunk 1]
```diff
@@ -56,6 +63,18 @@ export class MdListItem implements AfterContentInit {
 
   constructor(private _renderer: Renderer, private _element: ElementRef) {}
 
+  /** @internal */
+  handleFocus() {
+    console.log('focus');
```
Comment (kara) [inline src/components/list/list.ts]: Remove the console.logs?

Comment (robertmesserle) [inline src/components/list/list.ts]: Whoops.  Will do.

File: src/components/list/list.ts [hunk 2]
```diff
@@ -56,6 +63,16 @@ export class MdListItem implements AfterContentInit {
...
+  /** @internal */
+  handleFocus() {
+    this.hasFocus = true;
+  }
+
+  /** @internal */
+  handleBlur() {
+    this.hasFocus = false;
+  }
+
```
Comment (jelbourn) [inline src/components/list/list.ts]: Unit test for focus class?

Comment (robertmesserle) [inline src/components/list/list.ts]: Added.

**Comment by jelbourn** [comment]
LGTM
