### PR TITLE
fix(progress-bar): incorrectly handling current path when using hash location strategy

### LINKED ISSUE #12710: MatProgressBar _rectangleFillValue didn't display when routing is using hash
#### It‘s a Bug:
<mat-progress-bar [mode]='buffer'>

image

In the official website, it is normal.
but in my site:

image

u see, it’s blank!!!
In my router config, useHash is true, so my url is like:  `http://localhost:9621/#/preview/home`
This is the only point different from the official website.

I found  the bug:
image
If I adjust it as follows:
image
image
It's worked!

#### What is the expected behavior?
To normal.

#### What is the current behavior?
MatProgressBar buffer mode is blank.

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the progress bar prefixing the references incorrectly when the consumer is using the router's hash location strategy. The issue comes from the fact that the `Location` normalizes the `location.pathname` between the regular strategy and the hash one, whereas we need to use the exact same path as the `window.location`.

Fixes #12710.

### CODE REVIEW

File: src/lib/progress-bar/progress-bar.ts [hunk 1]
```diff
@@ -61,13 +85,16 @@ export class MatProgressBar extends _MatProgressBarMixinBase implements CanColor
...
+              @Optional() @Inject(MAT_PROGRESS_BAR_LOCATION) location?: MatProgressBarLocation) {
     super(_elementRef);
 
     // We need to prefix the SVG reference with the current path, otherwise they won't work
     // in Safari if the page has a `<base>` tag. Note that we need quotes inside the `url()`,
-    // because named route URLs can contain parentheses (see #12338).
-    this._rectangleFillValue = `url('${location ? location.path() : ''}#${this.progressbarId}')`;
+    // because named route URLs can contain parentheses (see #12338). Also we don't use
+    // `Location` from `@angular/common`, because we can't tell the difference between whether
+    // the consumer is using the hash location strategy or not.
```
Comment (jelbourn) [inline src/lib/progress-bar/progress-bar.ts]: Couldn't you do the same thing with `location.path()` from `@angular/common`'s `Location`?

Comment (crisbeto) [reply src/lib/progress-bar/progress-bar.ts]: That's what it used to do, but AFAIK Angular's `location.path` will normalize both of these to the same value: `/#/foo/bar` and `/foo/bar`.

Comment (jelbourn) [reply src/lib/progress-bar/progress-bar.ts]: Ah, got it. Can you expand the comment with that? 
```
...the consumer is using the hash location strategy or not because it normalizes both
`/#/foo/bar` and `/foo/bar` to the same thing
```

Comment (crisbeto) [reply src/lib/progress-bar/progress-bar.ts]: Done.
